server:
  port: 8091

spring:
  application:
    name: tss-api-gateway

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

zuul:
  # 忽略表达式
  ignored-patterns: /**/index.html
  # 路由前缀
  prefix: /api/v1
  # 关闭移除代理前缀
#  strip-prefix: false
  sensitiveHeaders: Set-Cookie
  routes:
    api-a:
      path: /api-s/**
      serviceId: TSS-STUDENT
      # strip-prefix: false
    api-b:
      path: /api-t/**
      serviceId: TSS-TEACHER
    api-c:
      path: /api-sy/**
      serviceId: TSS-SYY
    api-d:
      path: /api-a/**
      serviceId: TSS-ADMIN
      
  
    # \u591A\u5B9E\u4F8B\u914D\u7F6E\uFF0C\u672A\u7ED3\u5408eureka\u65F6
#    api-mult:
#      path: /api-mult/**
#ribbon:
#  eureka:
#    enabled: false
#api-mult:
#  ribbon:
#    listOfServers: http://dev.tss.com:8090,http://dev.tss.com:8091

feign: 
  hystrix: 
    enabled: false

ribbon:
  eager-load:
    enabled: true
    clients: tss-api-gateway
  ReadTimeout: 10000
  ConnectTimeout: 10000

  
# custom config
auth-server:
  serviceId: TSS-AUTH-SERVER
  
authentication: 
  oauth: 
    clientId: app
    clientSecret: app_20181206
    tokenValidityInSeconds: 1800
    scope: web