server:
  port: 8091

spring:
  application:
    name: tss-api-gateway

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

zuul:
  # 忽略表达式
  ignored-patterns: /**/index.html
  # 路由前缀
  prefix: /api/v1
  # 关闭移除代理前缀
#  strip-prefix: false
  sensitiveHeaders: Set-Cookie,Authorization
  routes:
    api-a:
      path: /api-a/**
      serviceId: TSS-STUDENT
      # strip-prefix: false
    api-b:
      path: /api-b/**
      serviceId: TSS-TEACHER
    api-c:
      path: /api-c/**
      serviceId: TSS-SYY
    api-d:
      path: /api-d/**
      serviceId: TSS-ADMIN
  
  
    # \u591A\u5B9E\u4F8B\u914D\u7F6E\uFF0C\u672A\u7ED3\u5408eureka\u65F6
#    api-mult:
#      path: /api-mult/**
#ribbon:
#  eureka:
#    enabled: false
#api-mult:
#  ribbon:
#    listOfServers: http://dev.tss.com:8090,http://dev.tss.com:8091